// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package http

import (
	"context"
	"github.com/compico/em-task/cmd/di"
	"github.com/compico/em-task/internal/pkg/config"
	"github.com/compico/em-task/internal/pkg/pgrepo"
	"github.com/compico/em-task/internal/pkg/service"
	"github.com/compico/em-task/pkg/logger"
	"github.com/compico/em-task/pkg/postgres"
	"github.com/compico/em-task/web"
	"github.com/compico/em-task/web/handlers"
	"github.com/compico/em-task/web/router"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, filepath string) (*App, func(), error) {
	configConfig, err := config.NewConfig(filepath)
	if err != nil {
		return nil, nil, err
	}
	httpServer := di.HttpServerConfigProvider(configConfig)
	slog := di.SlogConfigProvider(configConfig)
	level := di.SlogLevelProvider(slog)
	writer := di.SlogWriterProvider()
	slogReplacerAttribute := di.SlogReplacerAttrProvider()
	handlerOptions := di.SlogJsonHandlerOptionsProvider(slog, slogReplacerAttribute)
	handler := di.SlogJsonHandlerProvider(writer, handlerOptions)
	slogLogger := di.SlogProvider(handler)
	v := di.LoggerOptionsProvider()
	loggerLogger := logger.NewLogger(level, slogLogger, v...)
	database := di.DatabaseConfigProvider(configConfig)
	connectionConfig := di.ConnectionConfigProvider(database)
	pool, cleanup, err := postgres.NewConnection(ctx, connectionConfig)
	if err != nil {
		return nil, nil, err
	}
	db := postgres.NewDatabase(ctx, pool)
	healthCheckHandler := handlers.NewHealthCheck(loggerLogger, db)
	subscription := pgrepo.NewSubscriptionRepository(db)
	serviceSubscription := service.NewSubscription(subscription)
	createSubscriptionHandler := handlers.NewCreateSubscriptionHandler(loggerLogger, serviceSubscription)
	readSubscriptionHandler := handlers.NewReadSubscriptionHandler(loggerLogger, serviceSubscription)
	updateSubscriptionHandler := handlers.NewUpdateSubscriptionHandler(loggerLogger, serviceSubscription)
	deleteSubscriptionHandler := handlers.NewDeleteSubscriptionHandler(loggerLogger, serviceSubscription)
	listSubscriptionsHandler := handlers.NewListSubscriptionsHandler(loggerLogger, serviceSubscription)
	serveMux := router.NewServerMux(healthCheckHandler, createSubscriptionHandler, readSubscriptionHandler, updateSubscriptionHandler, deleteSubscriptionHandler, listSubscriptionsHandler)
	server := di.HttpServerProvider(httpServer, loggerLogger, serveMux)
	webServer := web.NewServer(server)
	app := &App{
		server: webServer,
		logger: loggerLogger,
		pg:     db,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

type (
	App struct {
		server web.Server
		logger logger.Logger
		pg     postgres.DB
	}
)
